name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')
    build:
      runs-on: ubuntu-latest

      steps:
        - name: build
            if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
            run: |
              echo say hello
      notify:
        needs: build
          runs-on: ubuntu-latest

          steps:
            - name: Checkout Synapse
              uses: actions/checkout@v1
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Build Synapse with Maven
              run: mvn clean install --file pom.xml

