name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get-name
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        run: |
          echo say hello ${{github.event.comment.body}}
          BODY=$(echo ${{github.event.comment.body}})
          a=( $BODY )
          COMP=${a[1]}
          echo $COMP
          echo "::set-output name=component::$COMP"
        id: component
      - name: Checkout Tests
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout REPO
        uses: actions/checkout@v1
        with:
          repository: Nirothipan/webhook
          ref: refs/heads/master
      - name: Run Tests
        run: |
          echo component name ${{ steps.component.outputs.component }}
#          mvn clean compile test-compile verify -Dgroup=smoke
#          mvn verify -pl :${{ steps.component.outputs.component }} -am
#          mvn surefire-report:failsafe-report-only -Daggregate=true
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
