name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Docker image to Google Cloud Run
        run: |
          echo say helloRAM

  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify Slack and send eMail
        run: |
          echo say hello
