name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Docker image to Google Cloud Run
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        run: |
          echo say helloRAM ${{github.event.comment.body}}

  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Synapse
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout MI
          uses: actions/checkout@v1
          with:
            repository: wso2/micro-integrator
            ref: refs/heads/master
            - name: Build MI with Maven
              run: mvn clean -Dsynapse.version=$(cat ../SYNAPSE_VERSION_FILE)
